/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.ud.semaforo.server.vista;

import co.com.ud.semaforo.server.dto.PlanSemaforicoDto;
import co.com.ud.semaforo.server.logica.EnvioMensajesLogica;
import co.com.ud.semaforo.server.logica.ReadFileJsonlogica;
import co.com.ud.semaforo.server.logica.ServerSemaforo;
import java.util.Objects;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author sierraj
 */
@Getter
@Setter
public class VistaServer extends javax.swing.JFrame {

    private SemaforoServerControlador semaforoServerControlador;
    private EjecucionCicloControlador ejecucionCicloModel;
    private PararCicloControlador pararCicloControlador;
    
    private ServerSemaforo serverSemaforo;
    private EnvioMensajesLogica envioMensajesLogica;
    
    @Setter @Getter
    private PlanSemaforicoDto planSemaforicoDto;
    /**
     * Creates new form VistaServer
     */
    public VistaServer(ServerSemaforo serverSemaforo, EnvioMensajesLogica envioMensajesLogica) {
        this.serverSemaforo = serverSemaforo;
        this.envioMensajesLogica = envioMensajesLogica;
        if(Objects.isNull(this.semaforoServerControlador)){
            this.semaforoServerControlador = new SemaforoServerControlador(this, serverSemaforo, this.envioMensajesLogica);
        }
        if(Objects.isNull(this.ejecucionCicloModel)){
            this.ejecucionCicloModel = new EjecucionCicloControlador(this, serverSemaforo, envioMensajesLogica);
        }
        if(Objects.isNull(this.pararCicloControlador)){
            this.pararCicloControlador = new PararCicloControlador(this);
        }
        initComponents();
        capturarEventos();
    }
    
    private void capturarEventos(){
        cargarInformacionBtn.addActionListener(semaforoServerControlador);
        ejecutarInicioBtn.addActionListener(ejecucionCicloModel);
        pararButton.addActionListener(pararCicloControlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargarInformacionBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        conectadosTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        ejecutarInicioBtn = new javax.swing.JButton();
        filesCombo = new javax.swing.JComboBox<>();
        pararButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timerText = new javax.swing.JTextField();
        cicloText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarInformacionBtn.setText("Cargar Informacion");
        cargarInformacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarInformacionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cargarInformacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        conectadosTextArea.setColumns(20);
        conectadosTextArea.setRows(5);
        conectadosTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(conectadosTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel3.setText("Conectados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        ejecutarInicioBtn.setText("Ejecutar");
        ejecutarInicioBtn.setEnabled(false);
        ejecutarInicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarInicioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ejecutarInicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        filesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intersección 1 (Calle 34 Cra 28)", "Intersección 2 (Cra 80 x Dg 43 Sur)", "Intersección 3 (Cra 13 x Calle 41)" }));
        getContentPane().add(filesCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        pararButton.setText("Parar");
        pararButton.setEnabled(false);
        getContentPane().add(pararButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel1.setText("Timer:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel2.setText("Ciclo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));
        getContentPane().add(timerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 180, -1));
        getContentPane().add(cicloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarInformacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarInformacionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarInformacionBtnActionPerformed

    private void ejecutarInicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarInicioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecutarInicioBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarInformacionBtn;
    private javax.swing.JTextField cicloText;
    private javax.swing.JTextArea conectadosTextArea;
    private javax.swing.JButton ejecutarInicioBtn;
    private javax.swing.JComboBox<String> filesCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pararButton;
    private javax.swing.JTextField timerText;
    // End of variables declaration//GEN-END:variables
}
